version: '3.9'

services:
  server:
    image: nginx:1.21.1
    container_name: nginx-
    ports:
      - 80:80
    networks:
      - net
    volumes:
      - ./confs/servers:/etc/nginx/conf.d/
      - ./backend:/var/www/html

  backend-test:
    build: ./backend
    container_name: backend-test
    networks:
      - net
    volumes:
      - ./backend:/var/www/html

  frontend-test: 
    build: ./frontend
    container_name: frontend-test
    ports:
      - 3000:3000
    networks:
      - net
    volumes:
      - ./frontend:/app
    command: ['npm', 'start']

  mysql-test:
    image: mysql:5.7
    container_name: mysql-test
    volumes: 
      - ./confs/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
    ports:
      - 3306:3306
    networks: 
      - net

networks: 
  net:
    driver: bridge
